#!/usr/bin/env python
"""License.sh

Usage:
  license-sh.py
  license-sh.py <path>
  license-sh.py (-h | --help)
  license-sh.py --version

Options:
  -h --help     Show this screen.
  --version     Show version.
"""
from license_sh.config import LICENSE_WHITELIST
from license_sh.reporters.ConsoleReporter import ConsoleReporter

VERSION = "1.0.0"

from docopt import docopt

from license_sh.project_identifier import get_project_types, ProjectType
from license_sh.runners.npm import NpmRunner
from license_sh.runners.python import PythonRunner

if __name__ == '__main__':
  arguments = docopt(__doc__, version=VERSION)

  path = arguments['<path>'] or '.'

  config = {}

  project_types = get_project_types(path)

  if ProjectType.PYTHON_PIPENV in project_types:
    runner = PythonRunner(path, config)
    root, license_map = runner.check()
    ConsoleReporter.output(root, [], license_map, LICENSE_WHITELIST)

  if ProjectType.NPM in project_types:
    runner = NpmRunner(path, config)
    root, license_map = runner.check()
    ConsoleReporter.output(root, [], license_map, LICENSE_WHITELIST)

